# Generated by Django 3.0 on 2021-01-22 07:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=100)),
                ('event_location', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=100)),
                ('organiser_email', models.EmailField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('vacancy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('participant_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('events_registerd', models.ManyToManyField(to='event_api_app.Events')),
            ],
        ),
    ]
